module.exports = {
  mode: 'watch',
  purge: {
    content: ['./src/{components,pages}/**/*.{js,ts,jsx,tsx}'],
    options: {
      safelist: [
        'text-dragon',
        'bg-rock',
        'text-rock',
        'bg-ghost',
        'text-ghost',
        'bg-steel',
        'text-steel',
        'bg-water',
        'text-water',
        'bg-grass',
        'text-grass',
        'bg-psychich',
        'text-psychich',
        'bg-ice',
        'text-ice',
        'bg-dark',
        'text-dark',
        'bg-fairy',
        'text-fairy',
        'bg-normal',
        'text-normal',
        'bg-fighting',
        'text-fighting',
        'bg-flying',
        'text-flying',
        'bg-posion',
        'text-posion',
        'bg-ground',
        'text-ground',
        'bg-bug',
        'text-bug',
        'bg-fire',
        'text-fire',
        'bg-electric',
        'text-electric',
        'bg-dragon',
        'text-dragon',
      ],
    },
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        rock: '#B69e31',
        ghost: '#70559b',
        steel: '#b7b9d0',
        water: '#6493eb',
        grass: '#74cb48',
        psychic: '#fb5584',
        ice: '#9ad6df',
        dark: '#75574c',
        fairy: '#E69EAC',
        normal: '#AAA67F',
        fighting: '#C12239',
        flying: '#A891EC',
        poison: '#A43E9E',
        ground: '#DEC16B',
        bug: '#A7B723',
        fire: '#F57D31',
        electric: '#F9CF30',
        dragon: '#7037FF',
        darkGray: '#212121',
        mediumGray: '#666666',
        lightGray: '#E0E0E0',
        backgroung: '#F7F7F7',
      },
      borderRadius: {
        '2lg': '10px',
      },
      fontSize: {
        xxs: [
          '10px',
          {
            lineHeight: '16px',
          },
        ],
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
