export enum pokemonType {
  'rock' = 'rock',
  'ghost' = 'ghost',
  'steel' = 'steel',
  'water' = 'water',
  'grass' = 'grass',
  'psychic' = 'psychic',
  'ice' = 'ice',
  'dark' = 'dark',
  'fairy' = 'fairy',
  'normal' = 'normal',
  'fighting' = 'fighting',
  'flying' = 'flying',
  'poison' = 'poison',
  'ground' = 'ground',
  'bug' = 'bug',
  'fire' = 'fire',
  'electric' = 'electric',
  'dragon' = 'dragon',
}
